feature: CSAM: Self-Generated Report UI - initial commit
techmatters/flex-plugins pull request #1010
Opened 2022-11-02 13:58 UTC by acedeywin

Primary reviewer: @stephenhand 

## Description

- New feature: CSAM: Self-Generated Report UI 
### Checklist
- [x] Corresponding issue has been opened
- [N/A] New tests added
- [N/A] Strings are localized
- [N/A] Tested for chat contacts
- [N/A] Tested for call contacts

### Related Issues
Fixes CHI-1406

### Verification steps

- Click on the "Offline Contact Record" button
- Select any of the categories
- Click on the "External Reports" dropdown button 

Note: This is the mock implementation, so there is not much going on here. There are lots of commented codes that will be used in the integration task. You will have to ignore the mess. No test has been implemented yet.

<img width="871" alt="Screenshot 2022-11-02 at 2 50 45 PM" src="https://user-images.githubusercontent.com/40429848/199507327-aa1f8b20-b472-4523-9f11-8fdcb063556d.png">

2022-11-03 21:16 UTC, stephenhand commented
This looks like it could use some DRYing up. Since a large amount of the UI is the same between the two types of CSAM reports, we should think about how we can extend & reuse more of the existing CSAM components for the new type of report rather than having a completely separate UI with lots of duplication

Similarly, the redux code could be consolidated into a single CSAM state. We are never going to be filling in both different types of CSAM report at the same time for the same task, so we don't need 2 separate, but very similar sets of states / reducers / actions defined - instead we should have a single state that can represent a partially complete counsellor reported or self-reported CSAM.

2022-11-03 21:18 UTC, stephenhand requested changes
This looks like it could use some DRYing up. 

Since a large amount of the UI is the same between the two types of CSAM reports, we should think about how we can extend & reuse more of the existing CSAM components for the new type of report rather than having a completely separate UI with lots of duplication

Similarly, the redux code could be consolidated into a single CSAM state. We are never going to be filling in both different types of CSAM report at the same time for the same task, so we don't need 2 separate, but very similar sets of states / reducers / actions defined - instead we should have a single state that can represent a partially complete counsellor reported or self-reported CSAM.

2022-11-10 12:19 UTC, acedeywin commented
@stephenhand I have refactored the code to be as DRY as possible.

2022-11-11 09:49 UTC, stephenhand reviewed
Few comments. 

Also we need a feature flag to be able to disable the new UI - it should toggle the rendering the new dropdown or the old button. This way we can roll out versions with this code but without the backend.

2022-11-11 09:49 UTC, stephenhand commented on plugin-hrm-form/src/components/tabbedForms/CSAMReportDropdown.tsx
> +          setCSAMType(true);
I don't think there should have to be 2 separate steps to set the CSAM type and route. We should be able to route to the page to set the CSAM report with the information about which of type it is in a single operation. The injected handler should take a parameter for the type and build the route accordingly

Also, we shouldn't use a boolean for CSAM type. Booleans should only be used in cases where 'true' and 'false' actually make sense, not just as a substitute for 2 arbitrary values.  Something informative like an enum or a union of string values should be used here instead.

2022-11-11 09:49 UTC, stephenhand commented on plugin-hrm-form/src/states/csam-report/reducer.ts
> +  createLinkForChild: boolean;
A global boolean like this would cause issues if anyone were ever to be filing CSAM reports on 2 tasks simultaneously. As commented elsewhere, it shouldn't be needed though, we can handle the CSAM type in the routing logic

2022-11-11 09:49 UTC, stephenhand commented on plugin-hrm-form/src/states/csam-report/types.ts
>  export type CSAMReportForm = {
We should have separate types for self-reported CSAM report and counsellor reported CSAM. We can have a union type for use in the functions but we should be using the type system to prevent people filling in properties for both types of report on the same instance

2022-11-14 12:29 UTC, stephenhand commented on plugin-hrm-form/src/components/CSAMReport/CSAMReportFormDefinition.ts
> +  childAge: {
I think the 2 types of CSAM reports are better with separate form definitions

2022-11-15 16:12 UTC, acedeywin commented on plugin-hrm-form/src/components/CSAMReport/CSAMReportFormDefinition.ts
> +  childAge: {
I have refactored this.

2022-11-15 19:39 UTC, stephenhand commented on plugin-hrm-form/src/components/CSAMReport/CSAMReport.tsx
> +  const childCSAMformElements = React.useMemo(() => {
Can we not have 1 form definition member, and we chose the definition object based on csamType?

2022-11-15 19:39 UTC, stephenhand commented on plugin-hrm-form/src/components/CSAMReport/CSAMReport.tsx
> +  csamType,
We still want csamType to be derived from the route rather than setting separately in redux

2022-11-16 13:03 UTC, acedeywin commented on plugin-hrm-form/src/components/CSAMReport/CSAMReport.tsx
> +  const childCSAMformElements = React.useMemo(() => {
@stephenhand There's no way this can be achieved since we have separate form definition objects, and we still need to reference each form element within the CSAMReportFormScreen.tsx file. As I pointed out yesterday, we would also need different form element definitions since we have separate form definition objects for the csam types.

2022-11-16 13:31 UTC, acedeywin commented on plugin-hrm-form/src/components/CSAMReport/CSAMReport.tsx
> +  csamType,
@stephenhand I am not sure I understand what you mean. Both `csamTypes` use the same route, which is `csam-report`.  Since the csamTypes can either be `self-report` or `counsellor-report`, the default type specified in the reducer is `counsellor-report` since that's the initial csam type that existed prior.

2022-11-16 13:45 UTC, stephenhand commented on plugin-hrm-form/src/components/CSAMReport/CSAMReport.tsx
> +  csamType,
Both csam types use the same route now. But they don't have to. There's no reason why there couldn't be a `self-report-csam-report` and a `counsellor-csam-report` subroute. seems like this would eliminate the need for a global csamType in redux, which as was noted before, could cause issues.

You could still pass the csamType down to the CSAMReportDefinition component, just infer it from the route

2022-11-16 14:00 UTC, stephenhand commented on plugin-hrm-form/src/components/CSAMReport/CSAMReport.tsx
> +  const childCSAMformElements = React.useMemo(() => {
We can use a union type here as well, pass one property that could be either type of definition down to CSAMReportFormScreen, then use a type guard / discriminator to determine which of the 2 types it is internally within CSAMReportFormScreen, which is where you need to know which of the 2 types it is

2022-11-16 14:15 UTC, stephenhand commented on plugin-hrm-form/src/components/CSAMReport/CSAMReport.tsx
> +  const childCSAMformElements = React.useMemo(() => {
Or, more simply, we could still have the 2 separate properties in CSAMReportFormScreen, but here we have a single function that produces both definitions, in an object or an array. Just means you don't duplicate the whole function

2022-11-16 14:44 UTC, acedeywin commented on plugin-hrm-form/src/components/case/ActionHeader.tsx
> +        {addedForCSAMCLC && (
@stephenhand This has been fixed.

2022-11-17 09:18 UTC, acedeywin commented on plugin-hrm-form/src/components/CSAMReport/CSAMReport.tsx
> +  csamType,
@stephenhand It's done.

2022-11-17 11:46 UTC, stephenhand commented on plugin-hrm-form/src/components/CSAMReport/CSAMReport.tsx
> +    const csamDefinitionObject = { ...definitionObject, ...childDefinitionObject };
Sorruy, this isn't what I was suggesting - apologies if you got that impression. My 2 suggestions were to either:

- use a union type to return an instance that could be the child definition OR the counsellor definition
- use a single function to return BOTH definitions, but both as separate objects, either as array items or object properties. i.e. `return [childReportDefinition, counsellorReportDefinition]` or `return {childReportDefinition, counsellorReportDefinition}`. You could then destructure them using `const [childReportDefinition, counsellorReportDefinition] = React.useMemo(() => { ...`

What you have here merges the two objects together into a combined blob.

2022-11-17 11:49 UTC, stephenhand reviewed
The routing changes look good- it's just the form definition management and the CLC naming that need looking at now

2022-11-17 17:04 UTC, acedeywin commented on plugin-hrm-form/src/components/CSAMReport/CSAMReport.tsx
> +    const csamDefinitionObject = { ...definitionObject, ...childDefinitionObject };
@stephenhand option one always returns an empty object `{}`. For option 2, I am not sure how to go about that, but I implemented something that may be close.

2022-11-17 20:27 UTC, stephenhand approved these changes

2022-11-17 20:28 UTC, stephenhand reviewed
Code looks ok to me now, I will test it in the morning

2022-11-18 08:05 UTC, stephenhand commented
Also, remember the story is not complete until this is merged up into Flex 2 - QA will be done on Flex 2

2022-11-18 08:08 UTC, stephenhand commented on plugin-hrm-form/src/components/CSAMReport/CSAMReport.tsx
> +    const csamDefinitionObject = { ...definitionObject, ...childDefinitionObject };
Option one wouldn't do that unless there was an issue with the implementation - but what you have is a version of option 2 which looks ok.

2022-11-18 10:02 UTC, merged

2022-11-18 11:38 UTC, janorivera commented
hey @acedeywin!  just wanted to say thanks for taking the time to update all the translation files!