Create subcategories shortcut links to counselor toolkit
techmatters/flex-plugins pull request #1200
Opened 2023-01-25 21:35 UTC by acedeywin

Primary reviewer: @stephenhand 

## Description

New feature - Create subcategories shortcut links to counsellor toolkit.

### Checklist
- [x] Corresponding issue has been opened
- [N/A] New tests added
- [x] Feature flags added
- [x] Strings are localized
- [N/A] Tested for chat contacts
- [x] Tested for call contacts

### Related Issues
Fixes CHI-1514

### Verification steps

- Make the ca-v1 the default helpline
- Select a category in "Categorize this Contact"
- Select Category in the Tab form
- Click on a dropdown
- Click on the information icon

Feature flag - `enable_counselor_toolkits`

<img width="1508" alt="Screenshot 2023-01-25 at 10 18 30 PM" src="https://user-images.githubusercontent.com/40429848/214695352-0cb20bad-56d2-41a8-bd71-9a6b50f5876e.png">
<img width="1508" alt="Screenshot 2023-01-25 at 10 19 14 PM" src="https://user-images.githubusercontent.com/40429848/214695519-e2592f31-2e77-4c6f-a61f-3a039ef48c65.png">
<img width="1508" alt="Screenshot 2023-01-25 at 10 19 23 PM" src="https://user-images.githubusercontent.com/40429848/214695561-a951d6e1-52e6-40c0-9296-1a11720eff06.png">

2023-01-27 09:17 UTC, stephenhand requested changes
I think it's mostly there, mainly the case list filtering needs a rework, but otherwise mainly renames & minor things

2023-01-27 09:17 UTC, stephenhand commented on plugin-hrm-form/src/components/contact/IssueCategorizationSectionForm.tsx
> +      getHelplineName,
We could probably just pass down the return value of getHelplineName rather than the function itself?

2023-01-27 09:17 UTC, stephenhand commented on plugin-hrm-form/src/services/ContactService.ts
> -const createCategory = <T extends {}>(obj: T, [category, { subcategories }]: [string, CategoryEntry]) => ({
Not sure why we have to loosen up the typing here?

2023-01-27 10:41 UTC, stephenhand requested changes
Not far off, it's just the case list filters that need a rework, the rest is mainly renames and small items

2023-01-27 13:55 UTC, acedeywin commented on plugin-hrm-form/src/components/caseList/filters/Filters.tsx
> +    value: { label: caseStatus.value },
@stephenhand We did. I realized it later.

2023-01-27 15:43 UTC, acedeywin commented on plugin-hrm-form/src/components/contact/ContactDetails.tsx
> +  task,
@stephenhand it shouldn't be there.

2023-01-31 09:11 UTC, stephenhand commented on plugin-hrm-form/src/components/caseList/filters/DateRangeFilter.tsx
> +  const { ...selected } = Object(filterOptions.find(([opt]) => opt === values[selectedOptionField]));
It doesn't seem like we've really gotten to the bottom of the issue - why does the original code seem to work fine when deployed, but not locally? This change is a workaround but it could have other knock on effects if we don't fully understand what's going on.

Have you tested the changes you have made when deployed to Aselo Development? I'd be concerned that fixing the local build might break the deployed one if we don't understand why they are behaving differently.

Also testing locally it still appears to be behaving a little strangely. It doesn't freeze any more, but you have to click every radio button in the date filter twice to get it to select properly. Clicking a radio button once clears out the selection, and you have to click again to get it to select the one you want.

If this is a pre-existing issue I think we should split it out into a separate PR. 

For this PR, we should just get the counsellor toolkit stuff ready (i.e. implement the other suggestions & get the tests passing) without this fix, and then address this separately

2023-02-02 10:24 UTC, acedeywin commented
@stephenhand, all feedback has been implemented.

2023-02-02 17:48 UTC, stephenhand reviewed
A few console.logs need removing and we need to use the config functions from hrmConfig - the other change can be in a follow up PR

2023-02-02 17:48 UTC, stephenhand commented on plugin-hrm-form/src/components/caseList/filters/CategorySection.tsx
> +  console.log('categoryName', categoryName);
Probably need to remove?

2023-02-02 17:48 UTC, stephenhand commented on plugin-hrm-form/src/components/caseList/filters/Filters.tsx
> +  console.log('statusValues here', statusValues);
Remove log

2023-02-02 17:48 UTC, stephenhand commented on plugin-hrm-form/src/components/caseList/filters/MultiSelectFilter.tsx
> +                console.log(
Remove

2023-02-02 17:48 UTC, stephenhand commented on plugin-hrm-form/src/components/contact/IssueCategorizationSectionForm.tsx
> +import { getConfig } from '../../HrmFormPlugin';
Use config methods from `hrmConfig`

2023-02-02 17:48 UTC, stephenhand commented on plugin-hrm-form/src/components/common/forms/categoriesTabGenerator.tsx
> +  return (
Seems like this dialog should be defined in IssueCategorizationSectionForm, then you only need to drill the open handler down to this level, and can have the close handler passed in directly?

Doesn't need for this PR - lets get it merged as is first, but lets try to do it in another one straight after this is merged would be good

2023-02-03 17:09 UTC, acedeywin commented on plugin-hrm-form/src/components/common/forms/categoriesTabGenerator.tsx
> +  return (
@stephenhand, I still need a bit more clarification here. But all other feedback has been implemented.

2023-02-03 20:26 UTC, stephenhand approved these changes

2023-02-04 00:28 UTC, nickhurlburt commented on plugin-hrm-form/src/components/common/forms/categoriesTabGenerator.tsx
> +/**
@acedeywin this comment block should go at the very top of the page, not below two other lines of comments. Please move this so that it is above the the current comments on Lines 1 and 2. No need for further review after making that change.

2023-02-04 13:37 UTC, stephenhand commented
Also, don't need to rereview but could you put some example links in the demo-v1 form definition for easier testing? Just a couple of categories with links to the Google home page would be fine

2023-02-06 09:49 UTC, merged