home page shortcut link to counselor toolkit
techmatters/flex-plugins pull request #1217
Opened 2023-02-02 10:21 UTC by acedeywin

Primary reviewer: @stephenhand 

## Description

- New feature: Home page shortcut link to counselor toolkit

### Checklist
- [x] Corresponding issue has been opened
- [N/A] New tests added
- [x] Feature flags added
- [x] Strings are localized
- [N/A] Tested for chat contacts
- [N/A] Tested for call contacts

### Related Issues
Fixes CHI-1547

### Verification steps

- Verify that there is an information icon on the side nav
- Click on the information Icon on the side nav
<img width="189" alt="Screenshot 2023-02-02 at 11 20 05 AM" src="https://user-images.githubusercontent.com/40429848/216298462-1c7cee79-6bca-46ef-9e3c-926855098e9f.png">

2023-02-02 11:55 UTC, stephenhand requested changes
Couple of changes, the only tricky one might be the CSS override

2023-02-02 11:55 UTC, stephenhand commented on plugin-hrm-form/src/components/toolkits/setUpCounselorToolkits.tsx
> +  featureFlags.enable_counselor_toolkits &&
We should also check if a kmsUrl is configured on the default helpline before showing this icon, in addition to the feature flag

2023-02-02 11:55 UTC, stephenhand commented on plugin-hrm-form/src/components/toolkits/setUpCounselorToolkits.tsx
> +import { getConfig } from '../../HrmFormPlugin';
`getConfig` from `HrmFormPlugin` is deprecated, use `getHrmConfig` from `hrmConfig` instead

2023-02-02 11:55 UTC, stephenhand commented on plugin-hrm-form/src/styles/global-overrides.css
> +div.css-1nnjdk7:hover {
I'm not sure what effect this is implementing but we can't override the autogenerated CSS class names like this - as well as being very obfuscated and hard to maintain, these generated names could change at any time, andf the effect would be lost

We need to try to achieve this with CSS that doesn't reference one of these class names, or if this is not achievable we need to go back to Jana & Dee

2023-02-02 13:54 UTC, acedeywin commented on plugin-hrm-form/src/components/toolkits/setUpCounselorToolkits.tsx
> +import { getConfig } from '../../HrmFormPlugin';
@stephenhand `featureFlags` does not exist in `getHrmConfig` but in `getConfig` of `hrmConfig`.

2023-02-02 15:29 UTC, stephenhand commented on plugin-hrm-form/src/components/toolkits/setUpCounselorToolkits.tsx
> +import { getConfig } from '../../HrmFormPlugin';
`getAseloFeatureFlags()` can be used to get the feature flages from `hrmConfig`

2023-02-03 17:21 UTC, acedeywin commented on plugin-hrm-form/src/components/toolkits/setUpCounselorToolkits.tsx
> +import { getConfig } from '../../HrmFormPlugin';
@stephenhand Done!

2023-02-03 20:24 UTC, stephenhand commented on plugin-hrm-form/src/components/toolkits/setUpCounselorToolkits.tsx
> +  featureFlags.enable_counselor_toolkits &&
@acedeywin - this one is still outstanding

2023-02-06 10:26 UTC, stephenhand approved these changes

2023-02-06 10:27 UTC, stephenhand requested changes
Oops, forgot there was 1 change still outstanding

2023-02-06 13:36 UTC, acedeywin commented on plugin-hrm-form/src/components/toolkits/setUpCounselorToolkits.tsx
> +  featureFlags.enable_counselor_toolkits &&
@stephenhand, I have implemented the changes. I did that in the `plugin-hrm-form/src/components/toolkits/CounselorToolkitSideLink.tsx` file.

2023-02-06 19:14 UTC, stephenhand approved these changes

2023-02-07 10:00 UTC, merged