Add some missing configurations in terraform- emoji picker flag and assets bucket url
techmatters/flex-plugins pull request #1320
Opened 2023-03-27 17:20 UTC by mythilytm

Primary reviewer: @

## Description
- There were some older service config state that was run (`terraform apply`) for an account. This PR adds emoji_picker and assets bucket url 

### Checklist
- [ ] Corresponding issue has been opened
- [ ] New tests added
- [ ] Feature flags added
- [ ] Strings are localized
- [ ] Tested for chat contacts
- [ ] Tested for call contacts

### Related Issues
Fixes #....

### Verification steps

2023-03-27 17:20 UTC, mythilytm commented on twilio-iac/aselo-as-production/main.tf
> +  assets_bucket_url = module.assets.assets_bucket_url
What is the path for assets bucket?

2023-03-27 17:56 UTC, robert-bo-davis commented on twilio-iac/aselo-as-production/main.tf
> +  assets_bucket_url = module.assets.assets_bucket_url
Adding here as well as slack for future reference

```
assets_bucket_url = "https://assets/-${lower(var.environment)}.[tl.techmatters.org](http://tl.techmatters.org/)"
```

or 

```
assets_bucket_url = "https://assets/-${lower(local.environment)}.[tl.techmatters.org](http://tl.techmatters.org/)"
```

depending on how the helpline is configured.

2023-04-04 17:28 UTC, robert-bo-davis requested changes

2023-04-04 17:28 UTC, robert-bo-davis commented on twilio-iac/aarambh-production/main.tf
> +  assets_bucket_url = "https://assets-${lower(var.environment)}.tl.techmatters.org"
Instead of passing this in as a variable, it can be generated in a local in the aws module [here](https://github.com/techmatters/flex-plugins/blob/master/twilio-iac/terraform-modules/aws/default/main.tf#L23).

That locals block will change to:

```
locals {
  docs_s3_location = "tl-aselo-docs-${lower(var.short_helpline)}-${lower(var.environment)}"
  chat_s3_location = "tl-public-chat-${lower(var.short_helpline)}-${lower(var.short_environment)}"
  assets_bucket_url = "https://assets-${lower(var.environment)}.tl.techmatters.org"
}
```

And can then be referenced with `local.assets_bucket_url`.

I don't see any modification to the aws module to actually do anything with that value (or accept the variable), yet.

Since this is a new variable, it only needs to be added to the "new style" of SSM param like in the [ssm.tf file](https://github.com/techmatters/flex-plugins/blob/master/twilio-iac/terraform-modules/aws/default/ssm.tf).

Let me know if you need anymore pointers!

2023-09-04 19:27 UTC, closed without merging