Bug fix: Welcome Message not getting triggered in Dev and Kek Vonal Staging
techmatters/flex-plugins pull request #1325
Opened 2023-03-30 15:30 UTC by acedeywin

Primary reviewer:

## Description

- Bug fix: Welcome Message not getting triggered in Dev and Kek Vonal Staging

### Checklist
- [x] Corresponding issue has been opened
- [N/A] New tests added
- [N/A] Feature flags added
- [N/A] Strings are localized
- [N/A] Tested for chat contacts
- [N/A] Tested for call contacts

### Related Issues
Fixes CHI-1768

### Verification steps

2023-04-05 09:56 UTC, stephenhand reviewed
Can you explain what you changed in this PR - the diffs are not very clean and it's very difficult to see what you changed inside the try catch blocks

2023-04-05 15:40 UTC, acedeywin commented
> Can you explain what you changed in this PR - the diffs are not very clean, and it's very difficult to see what you changed inside the try-catch blocks

The welcome message not getting triggered because the `getUnknownOption` function was breaking, and the error was not correctly handled. So the `try-catch` block was added to handle the error graciously and not break the entire code.

The main error was that `getUnknownOption` couldn't determine a valid unknown option for key. In this case, `unknownOption` didn't have the right value or `e.value === 'Unknown'` does not exist within the `json` files for Kek Vonal (Line 31 in prepopulateForm.ts). So I did a bit of a refactor on Line 31 in prepopulateForm.ts and added values for `unknownOption` in some of the `json` files.

2023-04-06 06:50 UTC, stephenhand requested changes
Please revert all the `try .. catch ... log` blocks. Swallowing errors is poor practice and should only be used in exceptional circumstances.

We should have proper error reporting for when prepopulation fails, i.e. catch the error at the top level and display an error to the user that there was a problem prepopulating the form, but that is out of scope for this ticket - for now, letting the errors throw & stopping the welcome message is better than swallowing them & hiding issues

2023-04-06 06:50 UTC, stephenhand commented on plugin-hrm-form/src/utils/setUpActions.ts
> +  if (TaskHelper.isChatBasedTask(task)) {
What is this change for? Is it part of you PR or a change from elsewhere?

2023-04-07 12:36 UTC, acedeywin commented on plugin-hrm-form/src/utils/setUpActions.ts
> +  if (TaskHelper.isChatBasedTask(task)) {
@stephenhand, Ooh, I removed it while troubleshooting. Thank you for spotting it. I will add it back.

2023-04-07 12:50 UTC, acedeywin commented
> Please revert all the `try .. catch ... log` blocks. Swallowing errors is poor practice and should only be used in exceptional circumstances.
> 
> We should have proper error reporting for when prepopulation fails, i.e. catch the error at the top level and display an error to the user that there was a problem prepopulating the form, but that is out of scope for this ticket - for now, letting the errors throw & stopping the welcome message is better than swallowing them & hiding issues

@stephenhand, I have fixed another bug in the `getAnswerOrUnknown` function. In the Kek Vonal case, the `key` (gender and age) is undefined since users don't answer any preEngagement question that involves it. So since `key` is undefined, the `isUnknownAnswer` variable throws an error because `isUnknownAnswer` only checks for two conditions - `answers[key].error` or `answers[key].answer === unknown`. So I added a third condition, `answers[key] === undefined`, which fixed the issue.

2023-04-07 19:34 UTC, stephenhand commented on plugin-hrm-form/src/utils/prepopulateForm.ts
> +    const isUnknownAnswer = answers[key] === undefined || answers[key].error || answers[key].answer === unknown;
```suggestion
    const isUnknownAnswer = !answers[key] || answers[key].error || answers[key].answer === unknown;
```

2023-04-07 19:34 UTC, stephenhand commented on plugin-hrm-form/src/utils/setUpActions.ts
> +  if (TaskHelper.isChatBasedTask(task)) {
You might have added back to the wrong if statement?

2023-04-07 19:34 UTC, stephenhand commented on plugin-hrm-form/src/utils/setUpActions.ts
> +  if (TaskHelper.isChatBasedTask(task) && !TransferHelpers.hasTransferStarted(task)) {
See below

2023-04-07 19:34 UTC, stephenhand commented on plugin-hrm-form/src/utils/mappers.ts
> +  try {
Can we remove this try ... catch ... log as well? Or is there a specific reason you are keeping it?

2023-04-08 06:59 UTC, acedeywin commented on plugin-hrm-form/src/utils/setUpActions.ts
> +  if (TaskHelper.isChatBasedTask(task)) {
Fixed.

2023-04-08 07:00 UTC, acedeywin commented on plugin-hrm-form/src/utils/prepopulateForm.ts
> +    const isUnknownAnswer = answers[key] === undefined || answers[key].error || answers[key].answer === unknown;
Done!

2023-04-08 07:00 UTC, acedeywin commented on plugin-hrm-form/src/utils/mappers.ts
> +  try {
Done!

2023-04-17 10:01 UTC, stephenhand approved these changes
LGTM

2023-04-17 12:39 UTC, merged