Alejandro/nz/stg tg setup
techmatters/flex-plugins pull request #1408
Opened 2023-05-09 16:45 UTC by janorivera

Primary reviewer:

## Description

### Checklist
- [ ] Corresponding issue has been opened
- [ ] New tests added
- [ ] Feature flags added
- [ ] Strings are localized
- [ ] Tested for chat contacts
- [ ] Tested for call contacts

### Related Issues
Fixes #....

### Verification steps

2023-05-14 21:15 UTC, robert-bo-davis commented on twilio-iac/terraform-modules/stages/provision/main.tf
> +  survey_workflow_sid = lookup(module.taskRouter.workflow_sids, "survey", "123")
We really need to lean up the aws module eventually... but for now, would [try()](https://developer.hashicorp.com/terraform/language/functions/try#examples) make more sense?

ex:
```
survey_workflow_sid = try(module.taskRouter.workflow_sids.survey, null)
```

2023-05-14 21:18 UTC, robert-bo-davis commented on twilio-iac/terraform-modules/stages/provision/main.tf
> +  survey_workflow_sid = lookup(module.taskRouter.workflow_sids, "survey", "123")
We could also just pass down `module.taskRouter.workflow_sids` and use the `try()` in a local to only create the new style SSM param (`/<environemnt>/twilioi/...`) if it is needed. The old style ssm params REALLY need to go away eventually.

2023-05-24 19:34 UTC, janorivera commented
ok @robert-bo-davis  OK I made some changes according to our conversation. I've applied it and tested it and it is working fine now.  This is ready for review. :)

2023-05-24 19:47 UTC, robert-bo-davis requested changes

2023-05-24 19:47 UTC, robert-bo-davis commented on twilio-iac/terraform-modules/aws/default/ssm.tf
> +  count       = var.survey_workflow_sid == "" ? 0 : 1
We are going to need this one to exist as well to prevent the same issues we encountered with the old style SSM params in the upcoming migration to the new SSM params.

2023-05-25 15:08 UTC, janorivera commented
ok, good catch! thanks @robert-bo-davis

2023-05-26 15:01 UTC, robert-bo-davis approved these changes
LGMT! Thanks

2023-05-26 16:28 UTC, merged