AS Staging Setup (Terraform)
techmatters/flex-plugins pull request #1522
Opened 2023-07-21 11:30 UTC by sinehome

Setting up staging environment through Terraform. 

Adding new staging.hcl file and updating the common.hcl file.

2023-07-21 14:31 UTC, GPaoloni reviewed
I left some questions and asking Bo's opinion. The changes for staging look good to me, I'm just doubtful on how much code we should share with development account.

2023-07-21 14:31 UTC, GPaoloni commented on twilio-iac/helplines/as/common.hcl
> +        templatefile : "/app/twilio-iac/helplines/cl/templates/workflows/master.tftpl"
Why are we using the `/cl` config here? If it is shared, makes sense to move it to a "shared location"?

2023-07-21 14:31 UTC, GPaoloni commented on twilio-iac/helplines/as/common.hcl
> +    }
I feel like this chunk of code here will affect the development and production accounts, since both use `helplines/as/common.hcl`, but at the same their are not provisioned from terraform, so I'm not sure. What do you think would be the best @robert-bo-davis? Moving this into `helplines/as/staging.hcl` or leaving it here?

2023-07-21 14:50 UTC, robert-bo-davis commented on twilio-iac/helplines/as/common.hcl
> +        templatefile : "/app/twilio-iac/helplines/cl/templates/workflows/master.tftpl"
Not sure, the workflow changes have mostly been handled by @janorivera

2023-07-21 14:53 UTC, robert-bo-davis commented on twilio-iac/helplines/as/common.hcl
> +    }
Ohhhh.... none of the as helplines have actually been migrated to terragrunt yet. This is all just placeholder. The lex provisioning is the first thing we will be adding in the new TG setup for the AS helplines, so everything unrelated to that is just copypasta that can be ignored until we start migrating them. If you want to clean them up, feel free, but it shouldn't actually impact anything unless it is impacting you're lex plan.

2023-07-21 14:53 UTC, robert-bo-davis commented on twilio-iac/helplines/as/common.hcl
> +        templatefile : "/app/twilio-iac/helplines/cl/templates/workflows/master.tftpl"
Ale, please disregard the tag and see note below.

2023-07-21 15:02 UTC, robert-bo-davis commented on twilio-iac/helplines/as/common.hcl
> +    }
I think it is fine in common until we migrate another environment. When we do, we'll need to sort out what goes where. I have a feeling that we will start from scratch (a brand new helpline) when we eventually provision development via terraform and that these common values are likely to be common across staging/production and that development will be the outlier so they will probably stay here anyway.

2023-07-21 18:26 UTC, sinehome commented on twilio-iac/helplines/as/common.hcl
> +        templatefile : "/app/twilio-iac/helplines/cl/templates/workflows/master.tftpl"
I had copied over the configurations from CL, will update that appropriately. For now we'll use the main template in `twilio-iac/helplines/templates/workflows/master.tftpl` instead of `twilio-iac/helplines/cl/templates/workflows/master.tftpl`

2023-08-03 16:24 UTC, janorivera requested changes
Also, I don't see any Channel definitions, like the web channel and the studio flow that it will use. Is that planned for a second stage?

2023-08-03 16:24 UTC, janorivera commented on twilio-iac/helplines/as/common.hcl
> +    contacts_waiting_channels         = ["web"]
contacts_waiting_channels can be removed now since this is part of a service configuration

2023-08-03 16:24 UTC, janorivera commented on twilio-iac/helplines/as/common.hcl
>      lex_bot_languages  = {
When deploying I would hold off on deploying the lex bots until my lex PR is merged. This will probably look different.

2023-08-03 16:24 UTC, janorivera commented on twilio-iac/helplines/as/common.hcl
> +        "target_workers" = "routing.skills HAS 'Messaging'",
Just confirm if we want to work with skills for this account?

2023-08-03 16:24 UTC, janorivera commented on twilio-iac/helplines/as/staging.hcl
> +    feature_flags = {
I think this is already out of date after Bo's PR got merged.

2023-08-08 12:56 UTC, janorivera commented
Things I think are missing:

- Channel definitions
- Update lex bot definitions
- remove feature flags

2023-11-08 10:30 UTC, closed without merging