[UI] Autocomplete
techmatters/flex-plugins pull request #1523
Opened 2023-07-21 12:17 UTC by acedeywin

Primary reviewer: @stephenhand 

- New feature: Resource search autocomplete

**Goal**: To see relevant suggestions for multiple individual search terms based on what users type in the Resource Search bar to find relevant resources more quickly for a specific service user.

**Current Problem**: Integration of the backend API is not working as expected. Throws a 500 error.

## Description

### Checklist
- [x] Corresponding issue has been opened
- [N/A] New tests added
- [N/A] Feature flags added
- [x] Strings are localized
- [N/A] Tested for chat contacts
- [N/A] Tested for call contacts

### Related Issues
Fixes [CHI-2009](https://tech-matters.atlassian.net/browse/CHI-2009)

### Verification steps

2023-07-21 13:03 UTC, stephenhand reviewed
If you mock out the data down in the `suggestResources` method in the `ResourcesService` rather than up in the component will allow you to build out more of your solution whilst the backend is fixed

For example you don't have anything to take the result of the API call and store it in the redux state, or to then feed it up into the UI - this could all be built with a mocked out API call

2023-07-21 13:03 UTC, stephenhand commented on plugin-hrm-form/src/services/ResourceService.ts
> +export const suggestResources = async (prefix: string, size: string): Promise<TaxonomyLevelNameCompletion> => {
Naming nit - It's suggesting search terms, not resources

2023-07-25 09:04 UTC, acedeywin commented on plugin-hrm-form/src/services/ResourceService.ts
> +export const suggestResources = async (prefix: string, size: string): Promise<TaxonomyLevelNameCompletion> => {
@stephenhand  - I renamed it to `suggestSearch`

2023-07-25 15:08 UTC, stephenhand requested changes
As a basic starting point it works well, however it needs some debouncing, because at the moment the keyboard input is choppy if you are typing quickly, and it spams a LOT of requests to the backend if you are typing fast.

I would start off with a component level debounce similar to the one in AseloMessageInput: https://github.com/techmatters/flex-plugins/blob/master/plugin-hrm-form/src/components/AseloMessaging/AseloMessageInput/AseloMessageInput.tsx

The difference is that this uses a hook form where as you will need a separate state item in the component for the latest version of the text

Reach out if you want more details about this

There also seems to be a large gap under the search box now?

2023-07-27 06:44 UTC, acedeywin commented
> https://github.com/techmatters/flex-plugins/blob/master/plugin-hrm-form/src/components/AseloMessaging/AseloMessageInput/AseloMessageInput.tsx

@stephenhand  - all feedback has been implemented.

2023-07-27 08:52 UTC, stephenhand commented on plugin-hrm-form/src/components/resources/search/SearchResourcesForm.tsx
> +  const handleSearch = debounce(
You are debouncing the wrong action for this - we want the `setGeneralSearchTermBoxText` call to be synchronously for each `onChangeSearch`. 

We want the call to `suggestSearch` to be a debounced handler for the `onChangeSearch` event, not an effect that gets run every time the form gets rerendered like it is currently.

2023-07-27 13:40 UTC, acedeywin commented on plugin-hrm-form/src/components/resources/search/SearchResourcesForm.tsx
> +  const handleSearch = debounce(
@stephenhand  - Yes, you are correct. I have implemented the debounce on action dispatch. Thank you.

2023-07-27 14:16 UTC, stephenhand approved these changes
Looks good and works well now!

2023-07-27 16:00 UTC, merged