Safernet Staging Lex Migration
techmatters/flex-plugins pull request #1577
Opened 2023-08-10 11:42 UTC by sinehome

Safernet Staging Lex Migration

- Adding Bot, Intent & SlotType JSON files
- Enabling Lex feature flag

2023-08-10 13:11 UTC, janorivera reviewed
I think you are missing some slot types as well

2023-08-10 13:49 UTC, dee-luo commented on twilio-iac/helplines/br/configs/lex/pt-br/intent/pre_survey.json
It looks like the question text doesn't match what's in Autopilot for their account. Can you double check the text on all of the questions? You're also missing a question on race.

2023-08-10 13:54 UTC, dee-luo requested changes
You'll also need to create a bot for the Reason Bot - which checks before the presurvey what the chatter is writing in about. It's called demo_chatbot in the Twilio account.

2023-08-10 20:23 UTC, dee-luo requested changes

2023-08-10 20:23 UTC, dee-luo commented on twilio-iac/helplines/br/configs/lex/pt-br/slot_types/ethnicity.json
The slot type values should match the values in the [contact form](https://github.com/techmatters/flex-plugins/blob/master/hrm-form-definitions/form-definitions/br/v1/tabbedForms/ChildInformationTab.json) and the existing [Autopilot Field Types](https://console.twilio.com/us1/service/autopilot/pre_survey_bot/autopilot-field-types?frameUrl=%2Fconsole%2Fautopilot%2Fpre_survey_bot%2Ffield-types%2FUB2ad1962502c8e85a6d0171987f4e0ec5%3F__override_layout__%3Dembed%26bifrost%3Dtrue%26x-target-region%3Dus1)

2023-08-10 20:23 UTC, dee-luo commented on twilio-iac/helplines/configs/lex/pt/slot_types/gender.json
Same comment as the ethnicity file - this needs to match [Autopilot Field Types](https://console.twilio.com/us1/service/autopilot/pre_survey_bot/autopilot-field-types?frameUrl=%2Fconsole%2Fautopilot%2Fpre_survey_bot%2Ffield-types%2FUBfecf1410c32dbe999265719573cf2c8a%3F__override_layout__%3Dembed%26bifrost%3Dtrue%26x-target-region%3Dus1) and [contact form values](https://github.com/techmatters/flex-plugins/blob/master/hrm-form-definitions/form-definitions/br/v1/tabbedForms/ChildInformationTab.json).

2023-08-10 20:38 UTC, dee-luo requested changes

2023-08-10 20:38 UTC, dee-luo commented on twilio-iac/helplines/br/configs/lex/pt-br/intent/contact_reason.json
Slot here should probably be called contactReason instead of aboutelf

2023-08-10 20:38 UTC, dee-luo commented on twilio-iac/helplines/br/configs/lex/pt-br/slot_types/contact_reason.json
Ok so the synonyms here are not correct. The synonyms should be words/phrases that match [these](https://console.twilio.com/us1/service/autopilot/demo_chatbot/autopilot-field-types?frameUrl=%2Fconsole%2Fautopilot%2Fdemo_chatbot%2Ffield-types%2FUB91c83f14091f3c5c57f1fb3df440bfbc%3F__override_layout__%3Dembed%26bifrost%3Dtrue%26x-target-region%3Dus1).

2023-08-10 20:40 UTC, dee-luo commented
@janorivera do you have an opinion on which files should be in the SaferNet specific config files vs. the general PT config files, or is the way it's currently organized okay?

2023-08-10 20:41 UTC, dee-luo reviewed
@sinehome this is a different helpline, SafeSpot is Jamaica. SaferNet doesn't have a TF studio flow, you'll want to just manage the Studio changes directly in the console. Can you revert this change?

2023-08-10 20:52 UTC, sinehome commented
@dee-luo , I've reverted the changes made on Safespot

2023-08-10 22:24 UTC, dee-luo requested changes
Almost there!

2023-08-10 22:24 UTC, dee-luo commented on twilio-iac/helplines/br/configs/lex/pt_br/slot_types/contact_reason.json
The values should just be numbers here, not the entire question. Then you will use the number value that is selected in Studio to determine the next action (either send a message or send the child to the pre-survey bot)

2023-08-10 22:24 UTC, dee-luo commented on twilio-iac/helplines/br/common.hcl
Not sure if this matters, but update task_language and helpline_language to be "pt-BR". Also remove "line" and "web" from contacts_waiting_channels

2023-08-10 22:24 UTC, dee-luo commented on twilio-iac/helplines/configs/lex/pt/intents/pre_survey.json
Can you add at the end of the rejection statement that the child is going to get transferred to a counsellor? Less abrupt.

2023-08-11 19:22 UTC, dee-luo approved these changes

2023-08-13 19:27 UTC, merged