Chi2229 casedoc lambda
techmatters/flex-plugins pull request #1666
Opened 2023-09-20 19:29 UTC by mythilytm

Primary reviewer:

## Description

### Checklist
- [ ] Corresponding issue has been opened
- [ ] New tests added
- [ ] Feature flags added
- [ ] Strings are localized
- [ ] Tested for chat contacts
- [ ] Tested for call contacts

### Related Issues
Fixes #....

### Verification steps

2023-09-21 21:20 UTC, robert-bo-davis commented on plugin-hrm-form/src/hrmConfig.ts
> +  const docsBucket = `tl-aselo-docs-${helplineCode}-${environment}`;
Someone updated the helplineCode attributes to be upper case.

We need to figure out who did that and why and if it is required, then change this to force the code into lower case.

2023-09-26 15:08 UTC, robert-bo-davis commented on plugin-hrm-form/src/components/common/forms/DownloadFile.tsx
> +  objectId: string;
Instead passing objectId alone, 
we probably want:

```
targetObject: {
	id: string
	type: SomeTypeRepresentingAvailableObjectTypes
}
```

and to pass that through the entire prop chain... until we can move to a context.

2023-09-26 15:11 UTC, robert-bo-davis requested changes

2023-09-26 15:11 UTC, robert-bo-davis commented on plugin-hrm-form/src/services/InsightsService.ts
> +    console.log('>>> mediaUrl', mediaUrl);
console.log

2023-09-26 15:19 UTC, GPaoloni reviewed
Two comments small notes

2023-09-26 15:19 UTC, GPaoloni commented on plugin-hrm-form/src/components/case/documentUploadHandler.ts
> +};
Extremely small note: 
You can 
```suggestion
export const bindFileUploadCustomHandlers = (caseId: number): CustomHandlers => {
  return {
    onFileChange: bindOnFileChange(caseId),
    onDeleteFile: bindOnDeleteFile(caseId),
  };
};
```
then when you call it you can remove one set of parenthesis.

2023-09-26 15:19 UTC, GPaoloni commented on plugin-hrm-form/src/services/ContactService.ts
> +// console.log(externalMediaPath); // Output should match that of generateExternalMediaPath
Can be removed?

2023-09-27 13:51 UTC, robert-bo-davis requested changes
See example refactor in #1688

2023-09-27 13:51 UTC, robert-bo-davis commented on plugin-hrm-form/src/components/case/ViewCaseItem.tsx
> +  };
I don't think the form this high in the stack needs to have any awareness of *how* the caseObj is going to be used further down the stack and we definitely don't want the calls further down the stack to have a difference between a case, contact, resource, csam or whatever other type we may pass through.

This is really just a temporary fix until we can move to a context, but I think it is important to keep generic components as generic as possible.

I have an example refactor PR up at #1688. Let's pair to go over the why's behind my changes when you are available.

2023-09-27 15:28 UTC, robert-bo-davis approved these changes
LGTM once final test is complete.

2023-10-04 16:55 UTC, merged