Chi 1435: Refactor contact saving logic redux promise - Part 2
techmatters/flex-plugins pull request #1692
Opened 2023-09-28 12:25 UTC by acedeywin

Primary reviewer: @stephenhand 

## Description

- **Feature refactor**: Refactor contact save logic into redux-promise middleware - part 2 (`connectToCase` and `submitContactForm`).
The ticket is the second part of the contact save logic refactor. It handles the refactoring of network calls for contact to be handled in our Redux layer rather than the component layer. This is the first PR for the `connectToCase` and `submitContactForm` services layer method.

- **Bug fix**: It also fixes the `Save and End Case` error.
- TODO: Implement units for the newly implemented actions and reducers. 

### Checklist
- [x] Corresponding issue has been opened
- [ ] New tests added
- [ ] Feature flags added
- [ ] Strings are localized
- [ ] Tested for chat contacts
- [ ] Tested for call contacts

### Related Issues
Fixes [CHI-1435](https://tech-matters.atlassian.net/browse/CHI-1435)

### Verification steps

- Create an offline contact
- Fill in all the necessary details
- Click on "Save Contact"
- Verify that the contact was saved successfully
- Repeat steps 1 and 2
- Click on "Add Contact to New Case"
- Click on "Save and End"
- Verify that contact was created and successfully added to the case

2023-10-05 14:16 UTC, stephenhand requested changes

2023-10-05 14:16 UTC, stephenhand commented on plugin-hrm-form/src/components/case/Case.tsx
> +      connectToCaseAsyncAction(savedContact.id, connectedCase.id);
I don't know if this is working the way to think it is - submitting the async action won't wait for the network call to complete - on the next render cycle, the task will be completed, regardless of whether the connectToCase call has completed or not.

If the idea is to do them sequentially, creating a separate async action which does both in sequence would be the simplest way. Otherwise you will have to put a state in the redux store and use that to control the sequence

2023-10-05 14:16 UTC, stephenhand commented on plugin-hrm-form/src/components/tabbedForms/BottomBar.tsx
> +      submitContactFormAsyncAction(task, contact, metadata, caseForm as Case);
Again, this logic probably isn't sequential any more, and should either be part of a single action or the sequence should be managed by state

2023-10-05 14:16 UTC, stephenhand commented on plugin-hrm-form/src/states/contacts/reducer.ts
> +  savedContact: {} as Contact,
We can't have global contact state like this,  the submitFormContact reducer needs to work with the tasks map for unsaved contacts

2023-10-06 10:57 UTC, acedeywin commented on plugin-hrm-form/src/states/contacts/reducer.ts
> +  savedContact: {} as Contact,
@stephenhand  - This has been handled.

2023-10-06 11:01 UTC, acedeywin commented on plugin-hrm-form/src/components/case/Case.tsx
> +      connectToCaseAsyncAction(savedContact.id, connectedCase.id);
@stephenhand  - Wouldn't it be better to implement a cleanup in the second `useEffect` that calls the `handleCompleteTask` method?

2023-10-06 11:07 UTC, stephenhand commented on plugin-hrm-form/src/components/case/Case.tsx
> +      connectToCaseAsyncAction(savedContact.id, connectedCase.id);
It isn't cleanup, it's a second step in the save operation. The idea of this refactor is to move the logic for handling this into redux, rather than relying on components to manage it, so it's better to handle the sequencing in the action creator or the redux state.

The component should just be able to send off a case for saving and be told when it's done, it shouldn't need to know about the separate backend calls involved in the save operation

2023-10-06 11:12 UTC, acedeywin commented on plugin-hrm-form/src/components/case/Case.tsx
> +      connectToCaseAsyncAction(savedContact.id, connectedCase.id);
@stephenhand  - Noted.

2023-10-06 14:56 UTC, stephenhand approved these changes
These look ok, we will probably need to be able to connect to case without submitting a contact in the future, but for now combining them is probably simplest

2023-10-06 15:39 UTC, merged