Unmask a phone number for a specific helpline
techmatters/flex-plugins pull request #1801
Opened 2023-11-07 18:19 UTC by mythilytm

Primary reviewer:

## Description
- By default, the caller's phone number is masked. KHP requested cases where the phone number needs to be revealed in an emergency. 
- Added a button that will toggle the visibility of this phone number. 
- Used MUI component Popper instead of a custom dialog because it gets cut off by the adjacent panels. 

### Checklist
- [x] Corresponding issue has been opened
- [n/a] New tests added
- [n/a] Feature flags added
- [n/a] Strings are localized
- [] Tested for chat contacts
- [] Tested for call contacts

### Related Issues
Fixes # https://tech-matters.atlassian.net/browse/CHI-2242

### Verification steps
<img width="315" alt="Screenshot 2023-11-07 at 1 13 41 PM" src="https://github.com/techmatters/flex-plugins/assets/102122005/ed93c9f4-e8a7-4966-8e12-fd87e4d1b359">

2023-11-07 18:23 UTC, mythilytm commented on plugin-hrm-form/src/HrmFormPlugin.tsx
> +  const maskIdentifiers = true;
Temporary for testing

2023-11-07 18:24 UTC, mythilytm commented on plugin-hrm-form/src/HrmFormPlugin.tsx
> +    if (setupObject.helplineCode === 'as' || setupObject.helplineCode === 'ca') Components.setUpViewMaskedVoiceNumber();
Temporary for testing

2023-11-08 20:42 UTC, robert-bo-davis requested changes
A few non critical notes. I think avoiding switching on helplineCode and only showing the component if the identifiers are masked are the only MUSTs. All of the rest are SHOULDs or COULDs most of which I'd like to have Gian's opinion on.

2023-11-08 20:42 UTC, robert-bo-davis commented on plugin-hrm-form/src/components/common/ViewTaskNumber.tsx
> +    setViewNumber(!viewNumber);
Would a single toggleViewNumber function make more sense than duplicating the same code in a handler?

2023-11-08 20:42 UTC, robert-bo-davis commented on plugin-hrm-form/src/HrmFormPlugin.tsx
> +    if (setupObject.helplineCode === 'as' || setupObject.helplineCode === 'ca') Components.setUpViewMaskedVoiceNumber();
I think we should probably use a configuration flag for this feature instead of a helplineCode switch. If it were me, I'd probably move the "switch" logic into the setUpViewMaskedVoiceNumber function so that all responsibility for the feature is delegated to that chunk of code, but I think that is more of a personal preference thing. We should definitely avoid switching on helplineCode though. 

The switch should also probably take into account if the user has `VIEW_IDENTIFIERS` permission as well. There is no reason to show the component if the user can already see the identifier, right?

2023-11-08 20:42 UTC, robert-bo-davis commented on plugin-hrm-form/src/components/common/ViewTaskNumber.tsx
> +      {renderTaskNumberPopper()}
Render functions are always a balancing act. I probably tend to overuse them and don't want to infect the rest of the team with my bad habits. @GPaoloni do you have an opinion about when to use them and when to avoid them?

2023-11-08 20:47 UTC, robert-bo-davis commented on plugin-hrm-form/src/components/common/ViewTaskNumber.tsx
> +      {renderTaskNumberPopper()}
I tend to use them for chunks of code that I think: Hmm... this chunk will probably be a separate component in the near future, may as well go ahead and segment it out. Or if there is more complexity to the "what should I display" than a `?: null` ternary. But those are just some general rules of thumb and this could very well be a remnant of my POC that I don't remember writing. 🤣

2023-11-08 20:58 UTC, robert-bo-davis commented on plugin-hrm-form/src/styles/HrmStyles.tsx
> +export const StyledUnmaskButton = styled(TransferStyledButton)`
I lost a comment, I think. Hmm. 

Do we want to bundle all of this into a component folder instead of spreading very related code across a bunch of global spaces?

Something like creating a `components/common/ViewTaskNumber` directory that has an icons directory, an index.tsx, and a styles.tsx so all of the related code lives together? @GPaoloni is there an existing standard for something like this?

2023-11-09 13:27 UTC, mythilytm commented on plugin-hrm-form/src/styles/HrmStyles.tsx
> +export const StyledUnmaskButton = styled(TransferStyledButton)`
Good point. I am curious what @GPaoloni suggests

2023-11-14 22:34 UTC, GPaoloni approved these changes
Code looks to me. One thing is that the client profiles identifier can still be seen

![Screenshot from 2023-11-14 19-30-11](https://github.com/techmatters/flex-plugins/assets/15805319/af43d5dd-86dc-4549-95a9-37e5ea62ebd0)

2023-11-14 22:53 UTC, mythilytm commented
To test this, the permission for `canViewIdentifiers` should be set to false and the newly added configFlag `enableUnmaskingCalls` should be set to true.
https://github.com/techmatters/flex-plugins/blob/CHI2242-mask-number/plugin-hrm-form/src/utils/setUpComponents.tsx#L234

2023-11-14 22:55 UTC, mythilytm commented
> Code looks to me. One thing is that the client profiles identifier can still be seen

For testing, the `canViewIdentifiers` permission should be set to false and the newly added configFlag `enableUnmaskingCalls` should be changed to true

2023-11-15 21:13 UTC, mythilytm commented
@GPaoloni 
I am unable to figure out why [separating the masking Identifiers logic](https://github.com/techmatters/flex-plugins/pull/1801/commits/03755c52c442828b3e94e9d4b688d4545f9014a8) is causing a unit test failure related to transfer button. 
https://github.com/techmatters/flex-plugins/actions/runs/6879656796/job/18712071058

I have tried debugging this but haven't figured it out. Behavior works fine when run locally. Curious if you have any thoughts.

2023-11-16 17:39 UTC, robert-bo-davis approved these changes
LGTM once LineChatChannel masking is verified working

2023-11-16 17:39 UTC, robert-bo-davis commented on plugin-hrm-form/src/channels/setUpChannels.tsx
> +// import { maskIdentifiersByChannel } from '../components/common/MaskingIdentifiers';
This probably needs to be re-enabled, right?

2023-11-16 18:03 UTC, robert-bo-davis commented on plugin-hrm-form/src/channels/setUpChannels.tsx
> -  if (maskIdentifiers) maskIdentifiersByChannel(LineChatChannel);
Is this change going to cause LineChatChannels to always be unmasked, even when they are meant to be masked?

2023-11-16 18:52 UTC, merged