Chi 1972 summary tab ability add contact case
techmatters/flex-plugins pull request #1810
Opened 2023-11-09 09:02 UTC by acedeywin

Primary reviewer: @stephenhand 

## Description

- New Feature: This is the final part for this [PR](https://github.com/techmatters/flex-plugins/pull/1788) that addresses how the search results that appear should be.

### Checklist
- [ ] Corresponding issue has been opened
- [ ] New tests added
- [ ] Feature flags added
- [ ] Strings are localized
- [ ] Tested for chat contacts
- [ ] Tested for call contacts

### Related Issues
Fixes [CHI-1972](https://tech-matters.atlassian.net/browse/CHI-1972)

### Verification steps

- Create an offline contact
- Verify that we have a new "Add to New Case” drop-up button with "New Case" and "Existing Case" as options
- The "New Case” button should behave the same as the previous “Add Contact to Case” button
- The “Existing Case” button should take you to the Search tab where the header would be "Search for Cases"
- Search for a Case
- Verify that the search results only return cases

2023-11-09 11:26 UTC, stephenhand requested changes

2023-11-09 11:26 UTC, stephenhand commented on plugin-hrm-form/src/components/NavigableContainer.tsx
> +import { setSearchExistingCase } from '../states/search/actions';
NavigableContainer is a generic navigation component, it should not have stuff specific to search in it. There is already a mechanism for injecting custom close behaviour via a function, we should use that

2023-11-09 11:26 UTC, stephenhand commented on plugin-hrm-form/src/states/search/reducer.ts
> +    case t.SEARCH_EXISTING_CASE: {
I think this property would be better implemented as an additional property of the navigation route (e.g. `{ route: 'search', subroute: 'form', action: 'select-case' }` & `{ route: 'search', subroute: 'case-result', action: 'select-case' }` rather than a property that needs to be switched on and off with a separate action

2023-11-09 16:21 UTC, acedeywin commented on plugin-hrm-form/src/states/search/reducer.ts
> +    case t.SEARCH_EXISTING_CASE: {
@stephenhand  - All feedback has been implemented

2023-11-10 13:12 UTC, stephenhand reviewed
Code now looks good except for one q

Testing it though, it doesn't seem to change the state of the 'Add to case' button to 'Added To Case' immediately after adding to a case. You can still add to case, and the search results show the case you added in the correct state, but still allows you to connect to other cases.

This leads me to think that the search results in redux state are being updated correctly, but the contact under existingcontacts is not? It's strange because adding a case via the search tab updates the state immediately.

2023-11-10 13:12 UTC, stephenhand commented on plugin-hrm-form/src/states/routing/types.ts
> -export type SearchRoute = RouteWithModalSupport & {
Why is `RouteWithModalSupport` removed? Search routes need to support modals because cases and contact details appear as modals over search results

2023-11-13 15:32 UTC, acedeywin commented on plugin-hrm-form/src/states/routing/types.ts
> -export type SearchRoute = RouteWithModalSupport & {
@stephenhand  - I can't recall removing this. It might have been when I was fixing the merge conflict. I will pull the update from master now.

2023-11-14 13:38 UTC, acedeywin commented
> Code now looks good except for one q
> 
> Testing it though, it doesn't seem to change the state of the 'Add to case' button to 'Added To Case' immediately after adding to a case. You can still add to case, and the search results show the case you added in the correct state, but still allows you to connect to other cases.
> 
> This leads me to think that the search results in redux state are being updated correctly, but the contact under existingcontacts is not? It's strange because adding a case via the search tab updates the state immediately.

@stephenhand - It’s not really clear to me because it works fine while testing it. Once a contact gets added to a case and you click on the Cancel button, you will see that the contact is already added to a case and you won’t be able to search or add a case to it. Unless maybe you mean something different?

2023-11-15 10:17 UTC, stephenhand approved these changes
LGTM

2023-11-15 13:55 UTC, merged