Gian chi 2550
techmatters/flex-plugins pull request #2086
Opened 2024-02-15 14:31 UTC by GPaoloni

## Description

### Checklist
- [ ] Corresponding issue has been opened
- [ ] New tests added
- [ ] Feature flags added
- [ ] Strings are localized
- [ ] Tested for chat contacts
- [ ] Tested for call contacts

### Other Related Issues

None

### Verification steps

2024-02-16 15:56 UTC, mythilytm commented on plugin-hrm-form/src/permissions/dev.json
> +  "viewProfile": [["everyone"]],
In the case of `"viewProfile": [],`, i.e., no one should be able to view, I can still get to any client profile from other means - through the yellow banner and search and case list views through `View Client`.

2024-02-16 16:06 UTC, mythilytm commented on plugin-hrm-form/src/components/profile/profileFlag/ProfileFlagEdit.tsx
> +          <ProfileFlagList {...props} enableDisassociate={canUnflagProfile} disassociateRef={disassociateRef} />
I tried the following: 
  `"flagProfile": [],
  "unflagProfile": [],
  `
  For `flagProfile` and `unflagProfile`, the user can't dispatch these actions, which is expected. However, the view still suggests otherwise. I think the user should not be able to do a drop-down action.

2024-02-16 16:11 UTC, mythilytm commented on plugin-hrm-form/src/components/profile/section/ProfileSectionView.tsx
I tried `"viewProfileSection": [],`. 
Just a thought, would it make more sense to either remove the Empty Notes section or communicate that there are "no notes available to view"

2024-02-16 16:18 UTC, mythilytm requested changes
There are a few minor issues related primarily to the appearance of elements when the end user does not have permission to access.

2024-02-16 16:35 UTC, mythilytm commented
Thanks for separating `ProfileDetailsSection` and `ProfileSectionGroup`. This is much cleaner. They can be moved to the `section` directory

2024-02-16 21:00 UTC, mythilytm approved these changes
Happy to get this into QA

2024-02-21 20:30 UTC, stephenhand approved these changes

2024-02-22 20:14 UTC, GPaoloni commented
@mythilytm Your changes look great to me, good to merge. Thank you very much :raised_hands: :rocket: !

2024-02-22 20:38 UTC, merged