CHI-2190: Contact Detail: Add to Existing Case
techmatters/flex-plugins pull request #2177
Opened 2024-03-21 13:56 UTC by acedeywin

## Description

- New feature: Contact Detail: Add to Existing Case
- Ability to select between add to new case or existing case
- The search cases screen should show up as a modal over the contact details page.
- After the contact is added to the case, it should close the Search Cases Modal and be back to the Contact Details Page, showing the blue banner.

### Checklist
- [x] Corresponding issue has been opened
- [ ] New tests added
- [ ] Feature flags added
- [ ] Strings are localized
- [ ] Tested for chat contacts
- [ ] Tested for call contacts

[CHI-2190](https://tech-matters.atlassian.net/browse/CHI-2190)

### Other Related Issues

None

### Verification steps

- Search for a contact
- Select a contact - there should be a blue banner if the contact has been added to a case or the "Add to case" button if vice versa.
- Click on the "Add to case" button and select the "Existing case" button
- Verify that you are routed to the search page with "Search for cases" as the header
- Search for your case
- Add the contact to a case
- Verify that you can see the blue banner after adding the contact to a case
- Click on "Remove from Case"
- Close the orange banner
- Verify that the "Add to case" button appears after closing the orange banner

[CHI-2190]: https://tech-matters.atlassian.net/browse/CHI-2190?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-03-22 13:13 UTC, mythilytm commented on plugin-hrm-form/src/components/tabbedForms/AddCaseButton.tsx
> +      <StyledAddNewCaseDropdown style={conditionalStyles}>
`dropdown` and `position` can be passed as optional props like this: 
<StyledAddNewCaseDropdown dropdown top (or bottom) />

In styles, you can define the CSS properties instead. 
type StyledAddNewCaseDropdownProps = {
  dropdown: boolean;
  position: 'top' | 'bottom';
}

const StyledAddNewCaseDropdown = styled.div<StyledAddNewCaseDropdownProps>`
  display: ${props => (props.dropdown ? 'block' : 'none')};
  ${props => props.position === 'top' ? 'bottom: 100%;' : 'top: 100%;'}
`;

// Usage
<StyledAddNewCaseDropdown dropdown={dropdown} position="top" />

2024-03-22 13:56 UTC, stephenhand requested changes

2024-03-22 13:56 UTC, stephenhand commented on plugin-hrm-form/src/states/contacts/types.ts
> +  standAloneContactId?: string;
Again, adding global state to redux is not an acceptable way to implement these sorts of features in most circumstances. We need to pass the contact ID down from the contact details page within the context of the operation.

I would suggest adding a `contextContactId` to the route for search and case routes, this can be set opening the modal and passed down tot the case search and the case page for the purposes of adding a case.

This would also be specified when opening the search or the new case modal from the tabbed form, so we would always use the contextContactId and can stop looking up the contact from the task directly in these components.

A refinement of this approach might be to add a generic `contextVars` property to routes, which always gets copied in full in the routing reducer when new routes or modals are added to the stack. You can see the same approach used for the `context` string var.

2024-03-25 14:00 UTC, acedeywin commented on plugin-hrm-form/src/states/contacts/types.ts
> +  standAloneContactId?: string;
@stephenhand - `contextContactId` has been added to routes.

2024-03-26 16:24 UTC, stephenhand reviewed
Couple of comments - also, do we not need to update the AddToCaseBanner.tsx to update us adding the contact to the case from the Case home page

2024-03-26 16:24 UTC, stephenhand commented on plugin-hrm-form/src/states/routing/types.ts
> +  contextContactId?: string;
Could we make this a only property for routes that it applies to i.e. the Case routes and the case search results / search form, rather than every route?

2024-03-26 16:24 UTC, stephenhand commented on plugin-hrm-form/src/components/tabbedForms/AddCaseButton.tsx
>  type OwnProps = {
Maybe we should move this button somewhere else, since we it's no longer only used in tabbed forms

2024-03-26 16:24 UTC, stephenhand commented on plugin-hrm-form/src/components/search/CasePreview/index.tsx
> +  const taskContact = isStandaloneITask(task)
We should pass the task contact ID as the route's contextContactId when we launch the search form from the tabbed forms, so that here we just look up the contectContextId here and on the case form, rather than having to check in 2 places

2024-03-26 18:11 UTC, acedeywin commented
> Couple of comments - also, do we not need to update the AddToCaseBanner.tsx to update us adding the contact to the case from the Case home page

@stephenhand  - Can you throw more light on this? I not clear what you mean.

2024-03-26 18:12 UTC, acedeywin commented on plugin-hrm-form/src/components/search/CasePreview/index.tsx
> +  const taskContact = isStandaloneITask(task)
@stephenhand  - Can you throw more light on this?

2024-03-26 18:13 UTC, acedeywin commented on plugin-hrm-form/src/components/tabbedForms/AddCaseButton.tsx
>  type OwnProps = {
@stephenhand - Can you throw more light on this? If I am to move it, where should I move it?

2024-03-26 18:22 UTC, stephenhand commented on plugin-hrm-form/src/components/search/CasePreview/index.tsx
> +  const taskContact = isStandaloneITask(task)
When we open a case search or a case from the tabbed forms when adding a new contact, we should pass the ID for the new contact as the contextContactId.

Then in here we only need to check for the contextContactId, we don't need to fall back to the task contact

2024-03-26 18:29 UTC, stephenhand commented
> > Couple of comments - also, do we not need to update the AddToCaseBanner.tsx to update us adding the contact to the case from the Case home page
> 
> @stephenhand - Can you throw more light on this? It's not clear what you mean.

If we want to be able to add an existing contact to an existing case from the Case home page, rather than the search preview (see https://marvelapp.com/prototype/8afa1ae/screen/92299919), the current code on master is not correct and will need updating. We will need to pass the contextContactId down on the route from the search page and change the button logic to use it

2024-03-27 15:32 UTC, stephenhand reviewed
Comments aside, the changes you make cover most of the points raised in the PR. There is still the piece of work to cover connecting existing cases to existing contacts from the case home page using the AddToCaseBanner.tsx component

2024-03-27 15:32 UTC, stephenhand commented on plugin-hrm-form/src/states/contacts/getContextContactId.ts
> +  const currentRoute = getCurrentTopmostRouteForTask(state[namespace].routing, taskSid);
You could just use `selectCurrentTopmostRouteForTask` here, `getCurrentTopmostRouteForTask` is kinda deprecated for use outside the module, we should try to remove the 'export' from it

2024-03-28 09:18 UTC, stephenhand reviewed
Almost there, couple of small comments

2024-03-28 09:18 UTC, stephenhand commented on plugin-hrm-form/src/components/caseMergingBanners/AddToCaseBanner.tsx
> +  const taskContact = selectContactStateByContactId(state, contactId)?.savedContact;
This is not the 'taskContact' any longer, because it isn't necessarily the context associated with a task. `contextContact`, or suimply `contact`, since this is the only contact this banner interacts with, might be a better name for this variable now

2024-03-28 09:18 UTC, stephenhand commented on plugin-hrm-form/src/components/tabbedForms/BottomBar.tsx
> +    openModal({ contextContactId: savedContact.id, route: 'search', subroute: 'form', action: 'select-case' });
@acedeywin has this been addressed?

2024-03-29 08:57 UTC, stephenhand reviewed
Some logic issues in the new code

2024-03-29 08:57 UTC, stephenhand commented on plugin-hrm-form/src/components/profile/IdentifierBanner/PreviousContactsBanner.tsx
> +  const contextContactId = selectContextContactId(state, taskSid, 'search', 'case-results');
It's my understanding that `selectContextContactId` only works when there is a contextContactId already on the route? Since PreviousContactsBanner is part of a tabbed form, this won't be the case, and the ID of the contact would need to be lookked up from the task using `selectContactFromTaskSid` or whatever the function is

2024-03-29 08:57 UTC, stephenhand commented on plugin-hrm-form/src/components/tabbedForms/TabbedFormsTabs.tsx
> +  const contextContactId = selectContextContactId(state, taskSid, 'search', 'case-results');
Same comment as previous contacts - the contextContactId is not on the route here & needs to be looked up from the task. In fact here we already map the correct contact Id as `contactId` here so you don't need to expose another one

2024-04-02 10:54 UTC, acedeywin commented on plugin-hrm-form/src/components/tabbedForms/TabbedFormsTabs.tsx
> +  const contextContactId = selectContextContactId(state, taskSid, 'search', 'case-results');
@stephenhand  - It's done.

2024-04-03 13:26 UTC, stephenhand approved these changes
Looks good now, thanks @acedeywin

2024-04-03 16:15 UTC, merged