CHI-2190: Add existing case to contact fixes
techmatters/flex-plugins pull request #2244
Opened 2024-04-11 18:52 UTC by acedeywin

## Description

- This PR addresses the QA feedback from the product team as seen [here](https://www.figma.com/file/3m7IJjYbussNcTs2VRhfYz/case-merging---QA?type=design&node-id=261-409&mode=design&t=4bGYTrp9CwtivH6N-0).

### Checklist
- [x] Corresponding issue has been opened
- [ ] New tests added
- [ ] Feature flags added
- [ ] Strings are localized
- [ ] Tested for chat contacts
- [ ] Tested for call contacts

### Other Related Issues

None

### Verification steps

[CHI-2190](https://tech-matters.atlassian.net/browse/CHI-2190)

### AFTER YOU MERGE

1. Cut a release tag using the Github workflow. Wait for it to complete and notify in the #aselo-deploys Slack channel.
2. Comment on the ticket with the release tag version AND any additional instructions required to configure an environment to test the changes.
3. Only then move the ticket into the QA column in JIRA

You are responsible for ensuring the above steps are completed. If you move a ticket into QA without advising what version to test, the QA team will assume the latest tag has the changes. If it does not, the following confusion is on you! :-P

2024-04-12 07:31 UTC, stephenhand commented on plugin-hrm-form/src/components/search/SearchForm/index.tsx
> +  const submitSearch = () => {
Is clearing the search form really a requirement now? This doesn't seem great as a UX. The idea of keeping the settings is that the user can refine their search iteratively without all having to re-enter all the same settingds each time. Keeping the settings is consistent with the Resource Search experience, which hads an explicit clear form button. 

Also this seems to be out of scope functionality changes for this story

2024-04-12 07:31 UTC, stephenhand commented on plugin-hrm-form/src/components/search/SearchForm/index.tsx
> +  const submitSearch = () => {
If this is to address an issue where the form to search for a case has the same settings that you originally searched for contacts on, then this is an artefact of the fact that we are only tracking the state of 1 search per task, and we need to be able to track multiple. 

I suspect this underlying issue will cause a lot of user facing bugs and needs to be addressed at the root cause, by changing our redux store to be able to track multiple search states per task

2024-04-12 10:22 UTC, acedeywin commented on plugin-hrm-form/src/components/search/SearchForm/index.tsx
> +  const submitSearch = () => {
@stephenhand - This was part of the feedback from the Product team, specifically Jana, as seen [here](https://www.figma.com/file/3m7IJjYbussNcTs2VRhfYz/case-merging---QA?type=design&node-id=261-409&mode=design&t=wgneHwOO82RCReAs-0).

2024-04-12 11:17 UTC, stephenhand commented on plugin-hrm-form/src/components/search/SearchForm/index.tsx
> +  const submitSearch = () => {
From that feedback, I'm assuming that the new behaviour of the original search form being blanked when you close the search results is undesirable and would be considered a bug

2024-04-19 13:15 UTC, stephenhand requested changes
Address comments, primarily use create and use contexts as discussed rathger than trying to just use the contact ID - also build is failing

2024-04-19 13:15 UTC, stephenhand commented on plugin-hrm-form/src/components/search/index.tsx
> +    searchContacts: (context: string) => searchContacts(dispatch)(taskId, context),
Can we make the searchContacts and searchCases APIs consistent?

2024-04-19 13:15 UTC, stephenhand commented on plugin-hrm-form/src/components/search/index.tsx
> +    currentRoute.route === 'search' && currentRoute.action === 'select-case' ? contextContactId : contactId || 'root';
```suggestion
    contextContactId ? `contact-${contextContactId} : 'root';
```

2024-04-19 13:15 UTC, stephenhand commented on plugin-hrm-form/src/components/search/index.tsx
> +  const searchRootId =
Confusing variable name, change to `searchContext`

2024-04-19 13:15 UTC, stephenhand commented on plugin-hrm-form/src/components/search/index.tsx
> +      handleCreateNewSearch(contextContactId);
Use searchContext, not ID

2024-04-19 13:15 UTC, stephenhand commented on plugin-hrm-form/src/components/tabbedForms/TabbedFormsSearch.tsx
> -      contactId={savedContact?.id}
This doesn't see like it should be changed

2024-04-19 13:15 UTC, stephenhand commented on plugin-hrm-form/src/states/contacts/types.ts
> +  contactId?: string;
Not needed

2024-04-19 16:51 UTC, acedeywin commented on plugin-hrm-form/src/components/search/index.tsx
> +    currentRoute.route === 'search' && currentRoute.action === 'select-case' ? contextContactId : contactId || 'root';
@stephenhand - `contactId || 'root' `is needed. `contactId` is for active contact.

2024-04-23 13:58 UTC, stephenhand requested changes

2024-04-23 13:58 UTC, stephenhand commented on plugin-hrm-form/src/___tests__/states/search/reducer.test.ts
> +    expect(tasks[task.taskSid]['']).toStrictEqual(newTaskEntry);
This seems strange - can we update the test to simulate passing a context?

2024-04-23 13:58 UTC, stephenhand commented on plugin-hrm-form/src/components/search/index.tsx
> +  const searchRootId =
I meant `searchRootId` should change to `searchContext`, not `contextContactId`

2024-04-23 13:58 UTC, stephenhand commented on plugin-hrm-form/src/states/search/reducer.ts
> +        [contact.id]: newTaskEntry,
It was line 108 I was thinking was unnecessary, not 107

2024-04-23 13:58 UTC, stephenhand commented on plugin-hrm-form/src/states/search/reducer.ts
> +          { ...value, context: { ...value.context, caseRefreshRequired: true } },
This will set the `caseRefreshRequired: true` for a context called `context` - whereas what we want to do is set it for all the contexts that currently exist under that task.

2024-04-23 13:58 UTC, stephenhand commented on plugin-hrm-form/src/states/search/reducer.ts
> +          { ...value, context: { ...value.context, contactRefreshRequired: true } },
This will set the `caseRefreshRequired: true` for a context called `context` - whereas what we want to do is set it for all the contexts that currently exist under that task.

2024-04-23 13:58 UTC, stephenhand commented on plugin-hrm-form/src/components/search/index.tsx
> +    selectContextContactId(state, taskId, 'search', 'form') ||
`selectContextContactId` shouldn't really need to take route and subroute parameters should it? The function itself can check if the current route is one of those which is valid to have a contextContactId, rather than the caller having to pass in the values to check against?

2024-04-23 15:18 UTC, acedeywin commented on plugin-hrm-form/src/components/search/index.tsx
> +    selectContextContactId(state, taskId, 'search', 'form') ||
@stephenhand - Passing in the route and subroute parameters makes the function dynamic so we can use it to determine what the current route is in real time.

2024-04-23 16:01 UTC, acedeywin commented on plugin-hrm-form/src/states/search/reducer.ts
> +          { ...value, context: { ...value.context, caseRefreshRequired: true } },
@stephenhand - The problem is how do I set it for all contexts? 

Value must be of type (parameter) value: { [context: string]: SearchStateTaskEntry}. How do I dynamically pass in context?

2024-04-23 16:32 UTC, stephenhand commented on plugin-hrm-form/src/components/search/index.tsx
> +    selectContextContactId(state, taskId, 'search', 'form') ||
The function already determines what the current route is in real time, it calls selectCurrentTopmostRouteForTask which always gives the current route for the task

The routes the support a `contextContactId` are static and don't change in real time, so can be checked by the function witrhout passing anything in I think?

2024-04-23 16:37 UTC, stephenhand commented on plugin-hrm-form/src/states/search/reducer.ts
> +          { ...value, context: { ...value.context, caseRefreshRequired: true } },
You can see a technique already being used in the layer above to ensure it is set on every task entry. where it converts the map to entries using `Object.entries`, updates each value using `.map` and then recreating the map using `Object.fromEntries`, thereby processing all the contexts in the map the same way

2024-04-25 08:31 UTC, stephenhand approved these changes
One optional comment - otherwise looks good once the tests pass

2024-04-25 08:31 UTC, stephenhand commented on plugin-hrm-form/src/components/profile/IdentifierBanner/PreviousContactsBanner.tsx
> +  const contextContactId =
You could use `selectContextContactId` here possibly?

2024-04-25 16:04 UTC, merged