CHI-2788: Support media in transcripts
techmatters/flex-plugins pull request #2377
Opened 2024-07-05 09:42 UTC by acedeywin

## Description

- New feature: This PR is to enable media display as link on Transcript. The Twilio conversations media resource API is called (another PR in Serverless), and the message object in the customer MessageList gets updated with the necessary data for media.

### Checklist
- [x] Corresponding issue has been opened
- [ ] New tests added
- [ ] Feature flags added
- [ ] Strings are localized
- [ ] Tested for chat contacts
- [ ] Tested for call contacts

### Other Related Issues

None

[CHI-2788](https://tech-matters.atlassian.net/browse/CHI-2811)

### Verification steps

- Search for a contact with that has uploaded media content (pdf, image files, etc)
- Load the transcript
- Verify that you can see the media file on the transcript
- Click on it to view

### AFTER YOU MERGE

1. Cut a release tag using the Github workflow. Wait for it to complete and notify in the #aselo-deploys Slack channel.
2. Comment on the ticket with the release tag version AND any additional instructions required to configure an environment to test the changes.
3. Only then move the ticket into the QA column in JIRA

You are responsible for ensuring the above steps are completed. If you move a ticket into QA without advising what version to test, the QA team will assume the latest tag has the changes. If it does not, the following confusion is on you! :-P

2024-07-05 16:00 UTC, stephenhand commented on plugin-hrm-form/src/components/contact/MediaSection/TranscriptSection.tsx
> +            const mediaUrl = await getMediaUrl(transcript.serviceSid, message.media.sid);
I don't think we should be generating temporary URLs for every media message in the transcript every time we open it.

Could we change the flow so that instead of a simple link for the media, we have a button that looks like a link, that calls the serverless service, gets the URL, then opens the media in a single operation, similar to how we do it when opening a case document?

2024-07-05 16:03 UTC, stephenhand commented on plugin-hrm-form/src/components/contact/MediaSection/TranscriptSection.tsx
> +            const mediaUrl = await getMediaUrl(transcript.serviceSid, message.media.sid);
Another approach could be to have the serverless service actually download the content once it has the URL and send it back to the client as the response - then simple links to the serverless service could be used in the transcript. However I think the client side button approach is best, it is consistent with what we do elsewhere and has less scope for having to fiddle around getting HTTP content headers right etc.

2024-07-08 12:22 UTC, acedeywin commented on plugin-hrm-form/src/components/contact/MediaSection/TranscriptSection.tsx
> +            const mediaUrl = await getMediaUrl(transcript.serviceSid, message.media.sid);
@murilovmachado  - I have implemented the feedback from @stephenhand. I went with the first approach, if you would please take a look at it since @stephenhand will be out this week.

2024-07-08 17:32 UTC, murilovmachado requested changes
It mostly looks good Stephen, but there's one thing that I think should be fixed:
The math to calculate the size of the media, I believe you're using the wrong multiplicator.

2024-07-08 17:32 UTC, murilovmachado commented on plugin-hrm-form/src/utils/selectMediaIcon.tsx
> +  image: 'jpeg' || 'jpg' || 'png',
Shouldn't it be using the single `|` in here instead of double `||`?

2024-07-08 17:32 UTC, murilovmachado commented on plugin-hrm-form/src/utils/selectMediaIcon.tsx
> +  return `${parseFloat((bytes / Math.pow(k, i)).toFixed(2))} ${sizes[i]}`;
I think `k` should be `1024` instead of `1000`.
Can you double-check that?

2024-07-09 11:06 UTC, acedeywin commented on plugin-hrm-form/src/utils/selectMediaIcon.tsx
> +  return `${parseFloat((bytes / Math.pow(k, i)).toFixed(2))} ${sizes[i]}`;
@murilovmachado - Yes, K should be 1024 but I made it 1000 to tidy up the display. So let's say the file is 1018 KB, that's what will be displayed. So I want it to accommodate only 999KB and when it gets to 1000, it's shortened to 1 MB. It may not be accurate but I notice that's how Twilio also handles their file size display.

2024-07-09 12:21 UTC, acedeywin commented on plugin-hrm-form/src/utils/selectMediaIcon.tsx
> +  image: 'jpeg' || 'jpg' || 'png',
@murilovmachado - I have made the necessary changes.

2024-07-09 16:16 UTC, murilovmachado approved these changes
Looks good to me, thanks!

2024-07-10 09:43 UTC, merged