Create CannedResponses.json
techmatters/flex-plugins pull request #450
Opened 2021-06-01 07:01 UTC by Humairaa127

ZM canned responses v1

2021-06-01 10:17 UTC, murilovmachado requested changes
There's a hidden **tab** in one of the strings. Let me know if you or I can remove it.

2021-06-01 10:17 UTC, murilovmachado commented on plugin-hrm-form/src/formDefinitions/v1/CannedResponses.json
> +    "text": "A condom is a sheath-shaped barrier device used during sexual intercourse to reduce the probability of pregnancy or a sexually transmitted infection. There are both male and female condo
This string contains a **tab** within it at `There are both male and female condoms. ; • (hidden tab here) Using a condom`
This is causing issues.

Can I just remove the tab part and it will be: `There are both male and female condoms. ; Using a condom`

2021-06-01 10:23 UTC, murilovmachado commented
Also, in order for these changes to be visible, we'll also need to add canned responses to `v1` definitions.
(I can do this on a separate PR)

On `src/formDefinitions/v1/index.ts`, we'll need to add:
```
...
cannedResponses: CannedResponses as CannedResponsesDefinitions,
...
```

2021-06-01 17:48 UTC, murilovmachado commented on plugin-hrm-form/src/formDefinitions/v1/CannedResponses.json
> +    "text": "A condom is a sheath-shaped barrier device used during sexual intercourse to reduce the probability of pregnancy or a sexually transmitted infection. There are both male and female condo
I'll fix this tomorrow and merge it.

2021-06-02 07:01 UTC, Humairaa127 commented on plugin-hrm-form/src/formDefinitions/v1/CannedResponses.json
> +    "text": "A condom is a sheath-shaped barrier device used during sexual intercourse to reduce the probability of pregnancy or a sexually transmitted infection. There are both male and female condo
fixed

2021-06-02 12:43 UTC, murilovmachado approved these changes

2021-06-02 12:44 UTC, merged