CHI 1121 Accessibility Enhancements for Case List (
techmatters/flex-plugins pull request #739
Opened 2022-05-06 02:00 UTC by mmythily

Primary reviewer:

## Description

- Removed 'expand' button and added a new styled component CLCaseIDButton based on button element for CaseId - keyboard buttons, tab and enter/space work
- Styling for CaseId column has been modified according to this [mock](https://marvelapp.com/prototype/6gcabah/screen/86290860)
- Tested that table content is accessible using screen readers.
- Added outline on case rows when hovered on mouse
- Rearranged and adjusted the table column widths to accommodate the new mocks. 

### Checklist
- [x] Corresponding issue has been opened
- [n/a] New tests added
- [x] Strings are localized
- [n/a] Tested for chat contacts
- [n/a] Tested for call contacts

### Related Issues
Fixes [#1121](https://bugs.benetech.org/browse/CHI-1121)

### Verification steps

2022-05-06 20:09 UTC, GPaoloni approved these changes
Couple of comments but it looks & works really good, great one! The styles are on point and I'm loving the hover on the cases haha.

Also, thanks for moving more code to TS!

2022-05-06 20:09 UTC, GPaoloni commented on plugin-hrm-form/src/styles/caseList/index.ts
> +      outlineColor: '#a0a8bd66',
Same comment on the outline as prior PR.

2022-05-06 20:09 UTC, GPaoloni commented on plugin-hrm-form/src/styles/caseList/index.ts
>  export const CLTableBodyFont = styled(FontOpenSans)<CLTableBodyFontProps>`
If this is not using `isOpenCase`, whoy don't just remove id? If the `CLTableBodyFontProps` ends up being empty you can just remove the type from here
`export const CLTableBodyFont = styled(FontOpenSans)`....`

2022-05-06 20:09 UTC, GPaoloni commented on plugin-hrm-form/src/styles/caseList/index.ts
> +  isOpenCase?: boolean;
Same as above.

2022-05-06 20:09 UTC, GPaoloni commented on plugin-hrm-form/src/translations/en-US/flexUI.json
> +  "CaseList-THCase": "Case",
This is the string I referred as `"Case"` in a prior comment :P

2022-05-06 20:09 UTC, GPaoloni commented on plugin-hrm-form/src/translations/en-US/flexUI.json
> +  "CaseList-StatusClosed": "Closed",
Are this being used?

2022-05-06 20:09 UTC, GPaoloni commented on plugin-hrm-form/src/translations/pt-BR/flexUI.json
> +  "CaseList-StatusClosed": "Fechado",
Same question as above.

2022-05-06 20:09 UTC, nickhurlburt requested changes
Several improvements but there are still some issues, especially around the table headers, which need to be resolved.

2022-05-06 20:09 UTC, nickhurlburt commented on plugin-hrm-form/src/translations/en-US/flexUI.json
> +  "CaseList-StatusOpen": "Open",
We should be showing the actual string of the case status, not just open or closed. But arguably that's a feature change and not an accessibility thing, so I've added that to [CHI-1178](https://bugs.benetech.org/browse/CHI-1178) instead. So no need to address in this PR.

2022-05-06 20:09 UTC, nickhurlburt commented on plugin-hrm-form/src/components/caseList/CaseListTableHeadCell.tsx
> +      <ArrowDownward
👍

2022-05-06 20:37 UTC, mmythily commented on plugin-hrm-form/src/components/caseList/CaseListTableRow.tsx
> +          <CLCaseIDButton aria-label={`Open Case ${caseItem.id}`} tabIndex={0} onClick={handleClickViewCase(caseItem)}>
Ah, thanks for clarifying :)

2022-05-06 20:37 UTC, mmythily commented on plugin-hrm-form/src/styles/caseList/index.ts
> +      outlineColor: '#a0a8bd66',
This particular one is for the the outline created when user hovers over the row with a mouse. In the mocks, it was this light grey....

2022-05-06 20:54 UTC, nickhurlburt commented on plugin-hrm-form/src/styles/caseList/index.ts
> +      outlineColor: '#a0a8bd66',
Yes, this isn't a focus outline, so it's fine

2022-05-06 20:55 UTC, nickhurlburt requested changes

2022-05-06 20:55 UTC, nickhurlburt commented on plugin-hrm-form/src/translations/en-US/flexUI.json
> +  "Case-CaseNumber": "Case",
I think this change has broken the case detail view:
![image](https://user-images.githubusercontent.com/10714292/167215169-54d8d380-5f35-4a4b-b1c4-341a745108dd.png)

That will need to be fixed

2022-05-06 21:22 UTC, mmythily commented on plugin-hrm-form/src/translations/en-US/flexUI.json
> +  "CaseList-StatusOpen": "Open",
I am using this like this:
` <Template code={`CaseList-Status${statusString}`} />`
I can remove it, but I am fairly certain this will work. For additional case statuses, the translations need to start with  **CaseList-Status**

2022-05-06 21:25 UTC, mmythily commented on plugin-hrm-form/src/translations/en-US/flexUI.json
> +  "CaseList-StatusOpen": "Open",
Also, I would have to remove Case Status unter the Case Id..
![Case Statuses](https://user-images.githubusercontent.com/42842977/167218488-bfd35819-88b7-4a56-a1b9-701e26e170a8.png)
.

2022-05-06 21:28 UTC, nickhurlburt commented on plugin-hrm-form/src/translations/en-US/flexUI.json
> +  "CaseList-StatusOpen": "Open",
I don't think that's necessary, though, because the form definitions already have the translated version. Checkout https://github.com/techmatters/flex-plugins/blob/master/hrm-form-definitions/form-definitions/br-v1/CaseStatus.json. We would just need to show the appropriate label.

While on the top, https://github.com/techmatters/flex-plugins/blob/master/hrm-form-definitions/form-definitions/za-v1/CaseStatus.json has an example of multiple case statuses.

2022-05-06 21:29 UTC, nickhurlburt commented on plugin-hrm-form/src/translations/en-US/flexUI.json
> +  "CaseList-StatusOpen": "Open",
I will note... there may be more complex reasons why this is hard in our existing system, and I may not fully understand those. But it seems redundant to me to need to maintain translations when we already have those strings in the form definitions.

2022-05-09 16:24 UTC, mmythily commented
I have worked on and resolved all of these points, except for these two, which need a closer look. 

https://github.com/techmatters/flex-plugins/pull/732#discussion_r862034714
I am not able to render a dynamic button that will focus and label the sort direction for screen readers for only the sortable headers. I end up transforming all  of the headers which is not desired. 

https://github.com/techmatters/flex-plugins/pull/739#discussion_r867226292
For this, I need some help figuring out the best practise for retrieving the form definition labels

2022-05-09 17:03 UTC, merged