CHI-1190: remove option to add contact to existing case
techmatters/flex-plugins pull request #784
Opened 2022-06-15 09:34 UTC by acedeywin

Primary reviewer: @mmythily @stephenhand 

## Description

- Feature modification: Remove the option to "Add Contact to Existing Case"

### Checklist
- [N/A] Corresponding issue has been opened
- [N/A] New tests added
- [N/A] Strings are localized
- [N/A] Tested for chat contacts
- [N/A] Tested for call contacts

### Related Issues
Fixes # N/A

### Verification steps

- Initial a call/chat/SMS, etc request as a user
- Accept incoming request
- Add new contact

<img width="1512" alt="Screenshot 2022-06-15 at 10 30 11 AM" src="https://user-images.githubusercontent.com/40429848/173795284-a2f27f76-7830-4bc3-af23-2460f6d10642.png">

2022-06-16 17:12 UTC, mmythily commented
Not related this PR, but PRs in general, it is helpful for reviewer on areas to focus on, you check off relevant items in checklist with [x]. These make it easier for the reviewer to know what to focus on. Also mention under Related Issues, the jira ticket identifier and a link. 

---
Checklist
[x] Corresponding issue has been opened
[N/A] New tests added
[x] Strings are localized
[N/A] Tested for chat contacts
[N/A] Tested for call contacts

Related Issues
Fixes # [1190](https://bugs.benetech.org/browse/CHI-1190)

2022-06-16 17:15 UTC, mmythily commented on plugin-hrm-form/src/permissions/demo.json
> +  "editContact": [["isSupervisor"]]
Good eye!

2022-06-16 17:57 UTC, mmythily requested changes
Overall functionality is great! Just some minor refactors

2022-06-16 17:57 UTC, mmythily commented on plugin-hrm-form/src/translations/en-US/flexUI.json
>    "BottomBar-AddToExistingCase": "Add to Existing Case",
"BottomBar-AddToExistingCase" string can be removed because it is not used anywhere

2022-06-16 17:57 UTC, mmythily commented on plugin-hrm-form/src/translations/es-ES/flexUI.json
>      "NotURLFieldError": "Este campo solo acepta URLs",
Actually, can you check with Joyce or Dee to check if "BottomBar-AddToExistingCase" / Add to Existing Case button is being removed for all helplines or just some select one(s).

2022-06-16 17:57 UTC, mmythily commented on plugin-hrm-form/src/components/tabbedForms/BottomBar.jsx
> -        <Menu anchorEl={anchorEl} open={isMenuOpen} onClickAway={() => this.setState({ isMenuOpen: false })}>
Since `isMenuOpen` and `anchorEl` are not being used, they can be removed from state in line 109, and 47, 48.  I might be mistaken, but since we are removing the menu, all mentions and logic using isMenuOpen and anchorEl can be removed / refactored.

2022-06-16 17:57 UTC, mmythily commented on plugin-hrm-form/src/components/tabbedForms/BottomBar.jsx
> -        <Menu anchorEl={anchorEl} open={isMenuOpen} onClickAway={() => this.setState({ isMenuOpen: false })}>
Same with imports in lines 6,9 and 14.

2022-06-16 17:57 UTC, mmythily commented on plugin-hrm-form/src/translations/en-US/flexUI.json
> +  "BottomBar-SaveCaseContact": "Save Contact",
I am curious if we can reuse / combine "BottomBar-SaveContact" and "BottomBar-SaveCaseContact". Or if they should be separate as you have done. You might want to check this also with Joyce or Dee

2022-06-16 18:06 UTC, mmythily commented
In CaseHome Component, we can still see this: I am not sure if this is desired and meant to be removed. 
![Save Contact options](https://user-images.githubusercontent.com/42842977/174136879-97825fac-a1be-46f4-a3bc-5b9f57ca2dd0.png)

2022-06-16 20:59 UTC, acedeywin commented on plugin-hrm-form/src/translations/es-ES/flexUI.json
>      "NotURLFieldError": "Este campo solo acepta URLs",
It's being removed from all helplines.

2022-06-17 10:20 UTC, acedeywin commented on plugin-hrm-form/src/translations/en-US/flexUI.json
> +  "BottomBar-SaveCaseContact": "Save Contact",
@mmythily  CaseHome Component uses "BottomBar-SaveContact" and "BottomBar-SaveCaseContact" which is why I created new objects. But I am going to adjust that on my next ticket to make them reusable.

2022-06-17 10:51 UTC, acedeywin commented on plugin-hrm-form/src/components/tabbedForms/BottomBar.jsx
> -        <Menu anchorEl={anchorEl} open={isMenuOpen} onClickAway={() => this.setState({ isMenuOpen: false })}>
Done.

2022-06-21 09:57 UTC, merged

2022-06-22 20:21 UTC, acedeywin reviewed
Implementing changes

2022-06-24 14:01 UTC, mmythily commented
The changes look good. Good work! https://github.com/techmatters/flex-plugins/pull/796 is not necessary. I would approve these changes.